# GitHub Pages Configuration

# Site settings
title: "Purcell - Refinaria de Ouro"
description: "Excelência em refinamento de ouro com tecnologia de ponta e tradição centenária"
url: "https://seuusuario.github.io"
baseurl: "/purcell"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
lang: pt-BR
author: "Purcell Refinaria de Ouro"

# Social
social:
  - platform: email
    link: "mailto:contato@purcell.com.br"
  - platform: phone
    link: "tel:+5511999999999"

# Exclude files
exclude:
  - README.md
  - favicon-generator.html
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/

# Include files
include:
  - _pages
  - assets
