# GitHub Pages Configuration for Static Site

# Site settings
title: "Purcell - Refinaria de Ouro Premium"
description: "Excelência em refinamento de ouro com tecnologia de ponta desde 2025"
url: "https://martimlourenco.github.io"
baseurl: "/Purcell"

# Language
lang: pt

# Exclude files from processing
exclude:
  - README.md
  - favicon-generator.html
  - .vscode/
  - .git/
